### ISSUE TITLE
How to Format Editor's Code 

### ISSUE THREAD

**Issue by rahat14** [Rosemoe/CodeEditor#108]
Need To Format code written in the editor by a button click.

**Comment by Rosemoe** [comment]
Currently no format server is provided as the sample is not an IDE app.
Sorry

**Comment by Rosemoe** [comment]
To format code, you should use an external library such as google's Java format library. And return formatted code in EditorLanguage's format(CharSequence) method.

**Comment by rahat14** [comment]
Any Idea on how to format Html Codes

**Comment by Rosemoe** [comment]
Sorry, I don't know, either

**Comment by rahat14** [comment]
It Can be with     implementation 'org.jsoup:jsoup:1.14.3' . by parsing the html to a document and getting back the Html from it
