### ISSUE TITLE
TextMate Line separator is cut off

### ISSUE THREAD

**Issue by BlueWhaleYT** [Rosemoe/CodeEditor#131]
Hi there, the line separator flags get some troubles while utilizing TextMate. Here is the condition:

![20211115_000352](https://user-images.githubusercontent.com/52563316/141688757-63c37b01-08c7-46fe-b850-2a004c5e0b9b.jpg)

Left: The vertical line doesn't cut off, which is implemented in JavaLanguage without TextMate.

Right: The vertical line cuts off, which is implemented in TextMate.

Thanks.

**Comment by Rosemoe** [comment]
Thanks for the feedback. Which version are you using?

**Comment by BlueWhaleYT** [comment]
currently, 0.8.3

**Comment by Rosemoe** [comment]
Check the [0.8.3](https://github.com/Rosemoe/CodeEditor/suites/4207759749/artifacts/108684151) sample, if possible?
If it is not working, try [0.8.4](https://github.com/Rosemoe/CodeEditor/suites/4349871625/artifacts/114140311) sample?
This bug should have been fixed in former version, I suppose.

**Comment by BlueWhaleYT** [comment]
Here is the screenshot of Sora editor demo in 0.8.4 version, it shows that the problem seems happening.
![Screenshot_20211115-002716_Sora-editor Demo](https://user-images.githubusercontent.com/52563316/141689530-b605160b-9748-49a9-874a-980ebcb41774.jpg)

as you see, the line doesn't end with the close brace, I noticed that this bug will happen when there is no character in the targeted line

**Comment by Rosemoe** [comment]
Thanks a lot for the tip.
I'll try to fix it as soon as possible.

**Comment by Rosemoe** [comment]
I am sorry to say that this is generated by textmate itself. However, the author of language-textmate said he will try to solve this.
