### ISSUE TITLE
TextMate Java comments in chinese characters can't be detected

### ISSUE THREAD

**Issue by BlueWhaleYT** [Rosemoe/CodeEditor#133]
Hi there, I am here to submit an issue regarding TextMate.
In TextMate, as far as what I am using right now i.e. TextMate Java. I noticed that the Chinese characters cannot be detected as a comment.

Here are the screenshots of Home-made and Demo respectively. (The Demo is in 0.8.4 version)

![Screenshot_20211115-220501_Sora-editor Demo](https://user-images.githubusercontent.com/52563316/141796109-ae9eda4d-aaeb-40da-ac90-6cbc1b96dd52.jpg)

In the picture, it can be seen that it breaks the syntax highlighting when the Chinese characters can't be detected as comments.

Thanks.

**Comment by Ninjacoderhsi** [comment]
I think it is a small flaw. You use English because it does not recognize many languages. Join the Telegram group for more help.

**Comment by Rosemoe** [comment]
@BlueWhaleYT I'll refer to the regex for the bug.
