### ISSUE TITLE
Introduce font cache

### ISSUE THREAD

**Issue by Rosemoe** [Rosemoe/CodeEditor#15]
After observing MT Manager's editor, I found his editor is much quicker than me.
This probably because it has some cache to measure text quickly.
Knowing this, I tested the speed of two ways to measure text. One with cache while another call native method directly.
When measuring a series of long text for several times, cached one is obvious quicker.
As the following images shows.
![Screenshot_2020-08-18-15-22-59-923](https://user-images.githubusercontent.com/28822819/90484422-bb184600-e168-11ea-9fd3-f615b7e1553b.png)
![Screenshot_2020-08-18-15-22-41-864](https://user-images.githubusercontent.com/28822819/90484441-c66b7180-e168-11ea-8318-186acb0344e0.png)
It is also faster in a single go:
![Screenshot_2020-08-18-15-25-24-101](https://user-images.githubusercontent.com/28822819/90484494-d6835100-e168-11ea-8dc0-c8d2563b8499.png)
And their results are the same.
So you may use font caches to equip the editor.

**Comment by Rosemoe** [comment]
Also a requirement to merge some rendering processes into drawing text, such as cursor and its handle , and text background to speed up.
Separating these out can cause drawing to have a worse performance.
Draw text without spans can be merge into draw text with spans. And drawTextDirect() does not highlight selected text. This merge can solve it.

**Comment by liyujiang-gzu** [comment]
只测量一次，之后重绘都从缓存取出，效果是很明显的样子。毕竟调用invalidate的地方太多，重会很频繁

**Comment by Rosemoe** [comment]
> 只测量一次，之后重绘都从缓存取出，效果是很明显的样子。毕竟调用invalidate的地方太多，重会很频繁

确实。
剩下几个过程也必须和文本绘制合并。
当光标在超长行最后，绘制需要花费2倍于光标在最前的时间。
