### ISSUE TITLE
[Bug] Edge Effects drawing not correct

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/CodeEditor#22]
when I scrolling down, sometimes the edge effect drawing from top and vice versa, as if everything is inverted

**Comment by liyujiang-gzu** [comment]
从左到右滑动，有时候边缘效果也会颠倒

**Comment by Rosemoe** [comment]
My way to determine is incorrect sometimes.
I'll fix it soon.

**Comment by Rosemoe** [comment]
I've tried to solve the problem. If it does not work, please reopen.
