### ISSUE TITLE
[Bug] Drawing not printing symbol not correct

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/CodeEditor#24]
Im, found when printing new text with whitespace, new whitespace not draw and eol symbol draw not correct
![Screenshot_20200904-211703_CodeEditorSample](https://user-images.githubusercontent.com/43380144/92273452-0dd95800-eef4-11ea-8804-1db5204b4381.jpg)

**Comment by Rosemoe** [comment]
Whitespaces are drawn only when they are at the start of line (set by sample app).
You can update the setting by yourself through setNonPrintablePaintingFlags(int)

**Comment by Rosemoe** [comment]
The problem of displaying eol wrongly is not happened on my application.
Did you modify drawRows()?
This:
```Java
// Draw hard wrap
if (lastVisibleChar == columnCount && (mNonPrintableOptions & FLAG_DRAW_LINE_SEPARATOR) != 0) {
    drawMiniGraph(canvas, paintingOffset, row, "↵", 0.9f);
}
```
must be placed before
```Java
paintingOffset = backupOffset;
```

**Comment by MrIkso** [comment]
> Did you modify drawRows()?

No

**Comment by Rosemoe** [comment]
Now fixed
This happens in EmptyLanguage
