### ISSUE TITLE
XML Analyzer/Language

### ISSUE THREAD

**Issue by MikeAndrson** [Rosemoe/CodeEditor#25]
It'd be cool to have a module for XML language too. We can't implement it using the simple way since XML needs tokenizing and analyzing for syntax highlighting, so the simple way is too limited..

**Comment by Rosemoe** [comment]
Glad to receive your feedback! I'll add it during new year vacation.

**Comment by HeyStudiosDEV** [comment]
Thanks :) any updates? happy new year by the way.
