### ISSUE TITLE
增加控制行号显示/隐藏的方法

### ISSUE THREAD

**Issue by GXSZone** [Rosemoe/CodeEditor#26]
增加行号显示的方法

**Comment by Rosemoe** [comment]
您好!
请问具体是什么方法呢?
控制行号显示/隐藏吗?
或者更多样式的行号?

**Comment by GXSZone** [comment]
控制行号显示/隐藏吗

**Comment by Rosemoe** [comment]
好的,这不久将会完成

**Comment by GXSZone** [comment]
> 您好!
> 请问具体是什么方法呢?
> 控制行号显示/隐藏吗?
> 或者更多样式的行号?



> 您好!
> 请问具体是什么方法呢?
> 控制行号显示/隐藏吗?
> 或者更多样式的行号?



> 好的,这不久将会完成

谢谢,节日快乐！

**Comment by Rosemoe** [comment]
现在,您已经可以通过CodeEditor#setLineNumberEnabled(boolean)和CodeEditor#isLineNumberEnabled()来控制和获取行号的显示状态了.
