### ISSUE TITLE
AutoCompleteWindow isn't shown until EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD is specified in onCreateInputConnection.

### ISSUE THREAD

**Issue by itsaky** [Rosemoe/CodeEditor#32]
AutoCompleteWindow isn't shown until EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD is specified in onCreateInputConnection.

If EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD along with EditorInfo.TYPE_TEXT_FLAG_NO_SUGGESTIONS is specified as input type, long pressing the backspace key in Soft Keyboard doesn't work. It acts as backspace was clicked only once.

[This](https://user-images.githubusercontent.com/46931079/107846621-2175dc80-6e0b-11eb-9932-8237ab90f221.mp4) is a video showing what's happens when I use EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD. Notice the long click on delete key. It doesn't work.

[This](https://user-images.githubusercontent.com/46931079/107846663-6ac62c00-6e0b-11eb-9594-6fe689adf8ff.mp4) video shows what happen when I remove the EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD flag. Due to text suggestions provided by keyboard, AutoCompleteWindow isn't shown. AutoCompleteWindow is only shown when I click the suggestion in keyboard.

**Comment by Rosemoe** [comment]
After testing, I found that when using NO_SUGGESTIONS the input method does not change its behavior at all and when using PASSWORD the keyboard just send ACTION_DOWN and ACTION_UP at the same time with long press.
I suppose that there is no solution to solve it by working on attributes passes to keyboard.
I also tried some methods on Stackflow, but none of them worked.

But it is possible to change editor's behavior to show completions even when the keyboard is showing its own suggestions. I have now added this to newest code in branch `main` and this feature is enabled by default.
If there is any side effect, please report to me.

**Comment by itsaky** [comment]
It's working better. But it still has some issues. Have a look at [this](https://user-images.githubusercontent.com/46931079/107852573-80514b00-6e37-11eb-852a-5260fc7a7ddf.mp4).

AutoCompleteWindow hides after typing second character. Everything else is good.

**Comment by Rosemoe** [comment]
Sorry for my carelessness.
I fixed the problem now.

**Comment by itsaky** [comment]
Okay. It's working. Thanks
