### ISSUE TITLE
AutoCompleteWindow is shown above the keyboard

### ISSUE THREAD

**Issue by itsaky** [Rosemoe/CodeEditor#33]
The editor should scroll to a position where the AutoCompleteWindow won't cover the keyboard.

[Video](https://user-images.githubusercontent.com/46931079/108242910-7c913180-7173-11eb-8320-8b54c5e2140e.mp4)

**Comment by Rosemoe** [comment]
Adding `android:windowSoftInputMode="adjustResize"` to your activity can solve this problem.

**Comment by itsaky** [comment]
Thanks a lot.
