### ISSUE TITLE
Add support for symbol pairs

### ISSUE THREAD

**Issue by Rosemoe** [Rosemoe/CodeEditor#36]
Match symbol pairs automatically on typing.
Such as '{', '(' and more

**Comment by RandunuK** [comment]
Is it ok to add single quote ***''*** and double quote ***""***
`            super.putPair('\'', new Replacement("''", 1));`
 `           super.putPair('\"', new Replacement("\"\"", 1));`
into `DefaultSymbolPairs()` in `SymbolPairMatch.java`
