### ISSUE TITLE
I can't find the languages

### ISSUE THREAD

**Issue by abdulmuhd** [Rosemoe/CodeEditor#37]
how to add the languages pleases e.g html, can't find it

**Comment by itsaky** [comment]
Maybe this is what you're looking for:
https://github.com/Rosemoe/CodeEditor/wiki/How-to-customize-your-language-for-editor

**Comment by Rosemoe** [comment]
I don't know exactly what you mean.
Maybe you want to add html language support to your project?
Just add
implementation 'com.github.Rosemoe.CodeEditor:language-html:0.4.0'
to your dependency.

**Comment by abdulmuhd** [comment]
yes that's what i want, thanks u
