### ISSUE TITLE
How to Set this line width?

### ISSUE THREAD

**Issue by RohitVermaOP** [Rosemoe/CodeEditor#38]
![IMG_20210313_132817](https://user-images.githubusercontent.com/56387351/111023681-62f4aa00-8400-11eb-9737-1ecc88b5110c.jpg)

**Comment by Rosemoe** [comment]
Use `CodeEditor#setBlockLineWidth(float)`
The unit of this method is **DP**.

**Comment by RohitVermaOP** [comment]
Ok, thanks!
