### ISSUE TITLE
Cannot turn off autocompletion on composing

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/CodeEditor#40]
Autocompletion on composing is not disabled for ` setAutoCompletionOnComposing(false)`  in CodeEditor.java.

**Comment by RandunuK** [comment]
change ` if ((mConnection.mComposingLine == -1 || mCompletionOnComposing) && endColumn != 0 && startLine == endLine) {` to ` if ((mConnection.mComposingLine == -1 && mCompletionOnComposing) && endColumn != 0 && startLine == endLine) {` in CodeEditor.java

**Comment by Rosemoe** [comment]
Thanks for the correction. I will try it soon after my exams.

**Comment by RandunuK** [comment]
Good luck in your exams Rosemoe.

**Steps to reproduce**

1. `setAutoCompletionOnComposing(false);` in CodeEditor.java initialize method.
2. Run the sample app
3. Type "System" 
After typing the complete word, autocomplete will appear.

**Comment by Rosemoe** [comment]
This switch is used for auto complete in composing text state.
A composing text is constantly marked by an underline in the editor. So this is not a bug.
You may want to add new method to disable the auto complete under all situations?
