### ISSUE TITLE
Enabling Samsung Keyboard's suggestions option makes the Editor crash. 

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#41]
when i open the editor for the first time, everything is fine,
but once i click on the editor to open the keyboard, it suddenly becomes red. that red color is being used in color.xml in my app as ColorControlHighlight.
can you fix it please, it's so annoying.

thanks.

https://user-images.githubusercontent.com/81700082/113169376-98015900-9256-11eb-956d-a3f9d09b2d7e.mp4

**Comment by Rosemoe** [comment]
Thanks for your feedback. I'll try to fix that soon.

**Comment by Rosemoe** [comment]
Now I tried to fix this in newest push.
Could you please check whether it works? My virtual device never happens this and my real device is Android 10.

**Comment by aliveness-e** [comment]
Hi,
The color tint has been fixed. but now there are even more bugs.
First: it crashes when i remove some text and  try to rewrite again (see the video).

https://user-images.githubusercontent.com/81700082/113517856-8dff9300-9593-11eb-8f02-265db7309341.mp4


Second: even though I've disabled auto completion (set AutoCompletionOnComposing to false), it still appears in some circumstances.

Thank you for your hard work.

**Comment by Rosemoe** [comment]
For the first problem, you can open menu and select "Open crash log" to get crash log. Send that to me if possible.
For the second, auto completion can be disabled by setAutoCompletionEnable(false)

**Comment by aliveness-e** [comment]
I'm sorry, but i can't get the crash log because I'm not using android studio. this bug occurs in the latest push by the way, it didn't exist before.

speaking of auto completion, I've already set it to false, but it keeps showing when i use keyboard suggestions, for example if i write  "pu" and then select "public" from the keyboard suggestions, auto completion window will appear.

https://user-images.githubusercontent.com/81700082/113521184-d5444e80-95a8-11eb-8e86-df77fd011563.mp4

**Comment by aliveness-e** [comment]
I'm sorry, I'm not using android studio. i can't get the crash log. this bug occurs in the latest push by the way, it doesn't exist before.

**Comment by aliveness-e** [comment]
Ok, i managed to get the crash log :


`java.lang.StringIndexOutOfBoundsException: Column 3 out of bounds.line: 0 ,column count:2
	at io.github.rosemoe.editor.text.Content.checkLineAndColumn(Content.java:762)
	at io.github.rosemoe.editor.text.Content.delete(Content.java:306)
	at io.github.rosemoe.editor.widget.EditorInputConnection.setComposingText(EditorInputConnection.java:324)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:399)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by Rosemoe** [comment]
I will research the log and fix this soon

**Comment by Rosemoe** [comment]
Could you please tell me what keyboard are you using？

**Comment by aliveness-e** [comment]
I'm using Samsung Keyboard. You are right, it's the keyboard, because when i tried Google Keyboard, that bug doesn't occur. I didn't know that the keyboard could actually cause such a problem 😬. Anyway, everything seems fine now as I'm using different keyboard.
Thanks a lot.

**Comment by aliveness-e** [comment]
I actually have noticed a strange behaviour using Samsung Keyboard in other editors too. The Keyboard itself has some bugs lol.

**Comment by Rosemoe** [comment]
Would you mind sending me your keyboard so that I can do further adaptations? As the keyboard can work in other editors without crashing, there is partly my fault to cause the bug.
I'll appreciate it if you could do that.

**Comment by aliveness-e** [comment]
No problem. By the way, this is a built-in keyboard that come pre-installed in Samsung devices. I'm not sure if it's going to work in other devices or not.
Here is the link of latest version that I'm using :

https://drive.google.com/file/d/1CpaTaXAuC_J4URvN0HmR4wR2pzA0rSM-/view?usp=sharing

**Comment by Rosemoe** [comment]
Yes. You are right. The keyboard always crashes on my device. I tried to download other versions by searching  but they crashed as the one you've provided.
Thanks a lot.

**Comment by aliveness-e** [comment]
By the way, the keyboard was working fine in the previous releases of your editor. it only crashes after the latest fix you've made.

**Comment by Rosemoe** [comment]
Thanks for the information. I‘ll review my changes.

**Comment by Rosemoe** [comment]
I tried to fix this in newest commit. Is it working?

**Comment by aliveness-e** [comment]
unfortunately, it still crash and shows the same error.
here is the new debug_logger log (i open the editor, then i typed "public", after that i removed the last letter "c", then i wrote it back, then it crashed) :

Code Editor : Connection reset
Code Editor : Get extracted text from input method
Code Editor : Receive update cursor anchor from input method
Code Editor : Finish composing text
Code Editor : setComposingText: text = p, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Monitor flag is set
Code Editor : setComposingText: text = pu, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = pup, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = pupl, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = pupli, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = puplic, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : beginBatchEdit()
Code Editor : endBatchEdit()
Code Editor : setComposingText: text = puplic, newCursorPosition = 1

**Comment by Rosemoe** [comment]
The log seems to have stopped before the deletion in editor.
Could you please enter some letters, delete one character and click 'Open debug log' to copy those logs in the menu?
Thanks a lot!

**Comment by aliveness-e** [comment]
here you go (using Samsung Keyboard): 
`Code Editor : Connection reset
Code Editor : Get extracted text from input method
Code Editor : Receive update cursor anchor from input method
Code Editor : Finish composing text
Code Editor : setComposingText: text = t, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Monitor flag is set
Code Editor : setComposingText: text = te, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = tes, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : setComposingText: text = test, newCursorPosition = 1
Code Editor : Get extracted text from input method
Code Editor : Get extracted text from input method
Code Editor : beginBatchEdit()
Code Editor : endBatchEdit()
Code Editor : Finish composing text
Code Editor : Receive update cursor anchor from input method
Code Editor : close connection
Code Editor : Finish composing text`



And here is the same test, but with different keyboard (Google Keyboard):
`Code Editor : Connection reset
Code Editor : beginBatchEdit()
Code Editor : getTextBeforeCursor()
Code Editor : getTextAfterCursor()
Code Editor : getSelectedText()
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : setComposingText: text = t, newCursorPosition = 1
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : setComposingText: text = te, newCursorPosition = 1
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : setComposingText: text = tes, newCursorPosition = 1
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : setComposingText: text = test, newCursorPosition = 1
Code Editor : endBatchEdit()
Code Editor : beginBatchEdit()
Code Editor : setComposingText: text = tes, newCursorPosition = 1
Code Editor : endBatchEdit()
Code Editor : Finish composing text
Code Editor : close connection
Code Editor : Finish composing text`

**Comment by aliveness-e** [comment]
it crashes when i enable predictive text option (suggestions), when i disable it, it works fine.


![Screenshot_20210409-122817_Samsung Keyboard](https://user-images.githubusercontent.com/81700082/114152765-b4c11f00-992f-11eb-8fd6-2a9904ac5371.png)

**Comment by Rosemoe** [comment]
I think now the problem is fixed.

**Comment by aliveness-e** [comment]
You got it! this bug has been fixed. it works fine now.
thank you so much.
