### ISSUE TITLE
Is it ok to add single quote '' and double quote "" to Default symbol pairs? 

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/CodeEditor#44]
Is it ok to add single quote '' and double quote "" to Default symbol pairs?

`super.putPair('\'', new Replacement("''", 1));`
`super.putPair('\"', new Replacement("\"\"", 1));`
into DefaultSymbolPairs() in SymbolPairMatch.java

 #36

**Comment by Rosemoe** [comment]
Yes. It's okay.

**Comment by Rosemoe** [comment]
It is recommended to add new symbol pairs by access CodeEditor#getOverrideSymbolPairs() to define pairs for all languages.
