### ISSUE TITLE
Add support for inserting symbols externally

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/CodeEditor#45]
expose commitTab method for insert tabs for python code editing

```/**
     * insert tab
     */
    public void insertTab() {
        commitTab();
    }
```

**Comment by Rosemoe** [comment]
I'll add a new channel to insert symbols in order to make  symbol helper view.

**Comment by Rosemoe** [comment]
This is supported now. 
Turn to MainActivity.java, SymbolInputView.java and SymbolChannel.java for further information.
