### ISSUE TITLE
custom code completion

### ISSUE THREAD

**Issue by catch11** [Rosemoe/CodeEditor#47]
Please add a custom code completion from a list.

also, all words between spaces will be appended to code completion as an identifier, can you please add option to disable this?

thank you.

**Comment by itsaky** [comment]
Could you please elaborate more about the feature/bug?

**Comment by Rosemoe** [comment]
I didn't get what you meaned.
Could you please describe it in detail?
You can customize your auto-completion items by implementing a EditorLanguage class and apply it to editor.

**Comment by catch11** [comment]
sorry i just didn't read the wiki, sorry for bothering 🙏
