### ISSUE TITLE
The CodeEditor should auto scroll horizontally when dragging selection/insert handle

### ISSUE THREAD

**Issue by itsaky** [Rosemoe/CodeEditor#50]
Currently, the CodeEditor only scrolls vertically (upward and downward) if the selection handle or insert handle is being moved by the user. The same behaviour should also be implemented when moved horizontally.

When moving the insert handle horizontally to the right, the CodeEditor scrolls. But this behaviour doesn't seem to be implemented for handle moving horizontally to the left.

Horizontal scroll doesn't work when moving the selection handles horizontally (both left and right).

**Comment by itsaky** [comment]
This video may help you understand what I'm saying :
https://user-images.githubusercontent.com/46931079/114141120-c8b85100-992e-11eb-8ff6-4e62513ebdcc.mp4

**Comment by Rosemoe** [comment]
I got it. Thanks!
