### ISSUE TITLE
Cannot get text action pop up without selecting a word

### ISSUE THREAD

**Issue by RandunuK** [Rosemoe/CodeEditor#51]
Text action popup cannot trigger without selecting a word. I think this block users pasting codes from clipboard.

![image (12)](https://user-images.githubusercontent.com/7280865/114365280-f7853000-9b97-11eb-9b8e-7691b9c6a82f.png)
user cannot paste to the cursor position

**Comment by Rosemoe** [comment]
This is not considered initially because most keyboards have its own paste button. I'll add this in next update.
