### ISSUE TITLE
Bug when paste a text from the keyboard.

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#56]
Hi,
i found a bug when i paste a text using my keyboard.
when i type something immediately after pasting a text using the paste option from the keyboard, it duplicate the text that has been pasted. but if i move the cursor to different position and then move it back, it works fine.
can you take a look at it please.
see the video below.
Thanks.

https://user-images.githubusercontent.com/81700082/116226026-8f237a80-a763-11eb-9ff9-7fe409748c01.mp4

**Comment by Rosemoe** [comment]
Is the keyboard Gboard(or others)? And the version of code editor and keyboard?

**Comment by aliveness-e** [comment]
Hi,
Thanks for your response. Yes I'm using the latest version of Google Keyboard :
10.4.04.361808908-release-arm64-v8a

and using the main project of this library (since you've fixed the issue #41).

**Comment by Rosemoe** [comment]
Now the problem will not occur. Any advice?

**Comment by aliveness-e** [comment]
Thanks!, I appreciate it.
there is one more thing related to auto indent :


https://user-images.githubusercontent.com/81700082/116705446-9950ad80-a9dd-11eb-92ec-0add4b009b33.mp4



(code editor language is Java Language)

**Comment by Rosemoe** [comment]
Ohhh, it's my fault.
I'll fix that tomorrow.
