### ISSUE TITLE
codeEditor.setTypefaceText() 设置英文字体时，若有中文变量参数，会导致所在行高亮错位。

### ISSUE THREAD

**Issue by xiaoyvyv** [Rosemoe/CodeEditor#6]
#### codeEditor.setTypefaceText() 设置英文字体时，若有中文变量参数，会导致所在行的高亮错位。
```java
codeEditor.setTypefaceText(Typeface.createFromAsset(activity.getAssets(),"fonts/Consolas.ttf"));
```

**Comment by Rosemoe** [comment]
不是很明白您的情况.
如果方便的话,是否可以提供具体的屏幕截图以及Consolas字体以便我检查问题所在?

**Comment by xiaoyvyv** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rosemoe/CodeEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 晚上7:56
收件人:&nbsp;"Rosemoe/CodeEditor"<CodeEditor@noreply.github.com&gt;;
抄送:&nbsp;"长江大学-玲"<1223414335@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Rosemoe/CodeEditor] codeEditor.setTypefaceText() 设置英文字体时，若有中文变量参数，会导致所在行高亮错位。 (#6)





 
不是很明白您的情况.
 如果方便的话,是否可以提供具体的屏幕截图以及Consolas字体以便我检查问题所在?

**Comment by Rosemoe** [comment]
在dev分支已解决
