### ISSUE TITLE
Input method moving cursor is not supported in the selected state

### ISSUE THREAD

**Issue by MoFanChenXuan** [Rosemoe/CodeEditor#60]
private boolean KEYCODE_SHIFT_STATUS;
    private boolean MoveLeftCursor = false;
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        switch (keyCode) {
            case KeyEvent.KEYCODE_SHIFT_LEFT:
            case KeyEvent.KEYCODE_SHIFT_RIGHT:
                KEYCODE_SHIFT_STATUS = true;
                return true;
            case KeyEvent.KEYCODE_DPAD_UP:
                //上
                if (KEYCODE_SHIFT_STATUS) {
                    KEYCODE_SHIFT_STATUS = false;
                    SelectUp();
                    return true;
                }
                break;
            case KeyEvent.KEYCODE_DPAD_DOWN:
                //下
                if (KEYCODE_SHIFT_STATUS) {
                    KEYCODE_SHIFT_STATUS = false;
                    SelectDown();
                    return true;
                }
                break;
            case KeyEvent.KEYCODE_DPAD_LEFT:
                //左
                if (KEYCODE_SHIFT_STATUS) {
                    KEYCODE_SHIFT_STATUS = false;
                    SelectLeft();
                    return true;
                }
                break;
            case KeyEvent.KEYCODE_DPAD_RIGHT:
                //右
                if (KEYCODE_SHIFT_STATUS) {
                    KEYCODE_SHIFT_STATUS = false;
                    SelectRight();
                    return true;
                }
                break;
            default : break;
        }
        return super.onKeyDown(keyCode, event);
    }

    /*上*/
    private void SelectUp() {
        Cursor cursor = getCursor();
        //左
        int leftLine = cursor.getLeftLine();
        int leftColumn = cursor.getLeftColumn();
        //右
        int rightLine = cursor.getRightLine();
        int rightColumn = cursor.getRightColumn();
        //选择状态
        if (cursor.isSelected() && !MoveLeftCursor) {
            rightLine = rightLine > 0 ? rightLine - 1: 0;
            int max_column = getText().getColumnCount(rightLine);
            rightColumn = Math.min(rightColumn, max_column);
            if (rightLine > leftLine || (rightLine == leftLine && rightColumn >= leftColumn)) {
                //移动了右光标
                MoveLeftCursor = false;
                setSelection(leftLine, leftColumn, rightLine, rightColumn);
                //显示右光标的位置
                ensureRightCursorVisible(cursor);
            }
            else {
                //移动了左光标
                MoveLeftCursor = true;
                setSelection(rightLine, rightColumn, leftLine, leftColumn);
                //显示左光标的位置
                ensureLeftCursorVisible(cursor);
            }
        }
        else {
            if (leftLine == 0) {
                //当前行为0,再向上列必须为0
                //在第一行向上
                leftColumn = 0;
            }
            else {
                leftLine = leftLine > 0 ? leftLine - 1: 0;
                int max_column = getText().getColumnCount(leftLine);
                leftColumn = Math.min(leftColumn, max_column);                
            }
            //向上，此时移动的一定是左光标
            //移动了左光标
            MoveLeftCursor = true;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示左光标的位置
            ensureLeftCursorVisible(cursor);
        }
    }

    private void SelectDown() {
        Cursor cursor = getCursor();
        int leftLine = cursor.getLeftLine();
        int leftColumn = cursor.getLeftColumn();
        //右
        int rightLine = cursor.getRightLine();
        int rightColumn = cursor.getRightColumn();
        //选择状态
        if (cursor.isSelected() && MoveLeftCursor) {
            int max_line = getText().getLineCount() - 1;
            leftLine = leftLine < max_line ? leftLine + 1: max_line;

            int max_column = getText().getColumnCount(leftLine);
            leftColumn = Math.min(leftColumn, max_column);

            if (leftLine < rightLine || (leftLine == rightLine && leftColumn <= rightColumn)) {
                //移动了左光标
                MoveLeftCursor = true;
                setSelection(leftLine, leftColumn, rightLine, rightColumn);
                //显示左光标的位置
                ensureLeftCursorVisible(cursor);
            }
            else {
                //移动了右光标
                MoveLeftCursor = false;
                setSelection(rightLine, rightColumn, leftLine, leftColumn);
                //显示右光标的位置
                ensureRightCursorVisible(cursor);
            }
        }
        else {
            //此时上次移动的是右光标
            int max_line = getText().getLineCount() - 1;
            //在rightLine+1前便是最大行数则,此次行与列皆是最大值
            if (rightLine == max_line) {
                //处理最后一行
                int max_column = getText().getColumnCount(rightLine);
                rightColumn = max_column;
            }
            else {
                rightLine = rightLine < max_line ? rightLine + 1: max_line;
                int max_column = getText().getColumnCount(rightLine);
                rightColumn = Math.min(rightColumn, max_column);
            }
            //移动了右光标
            MoveLeftCursor = false;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示右光标的位置
            ensureRightCursorVisible(cursor);
        }
    }

    private void SelectLeft() {
        Cursor cursor = getCursor();
        int leftLine = cursor.getLeftLine();
        int leftColumn = cursor.getLeftColumn();

        int rightLine = cursor.getRightLine();
        int rightColumn = cursor.getRightColumn();

        //选择状态
        if (cursor.isSelected() && ! MoveLeftCursor) {

            if (rightColumn > 0) {
                rightColumn--;
            }
            else {
                if (rightLine == 0) {
                    rightLine = 0;
                }
                else {
                    rightLine = rightLine > 0 ? rightLine - 1: 0;
                    int max_column = getText().getColumnCount(rightLine);
                    rightColumn = max_column ;//> 0 ? max_column - 1 : max_column;
                }
            }
            //移动了右光标
            MoveLeftCursor = false;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示右光标的位置
            ensureRightCursorVisible(cursor);
        }
        else {
            if (leftColumn > 0) {
                leftColumn--;
            }
            else {
                if (leftLine == 0) {
                    leftColumn = 0;
                }
                else {
                    leftLine = leftLine > 0 ? leftLine - 1: 0;
                    int max_column = getText().getColumnCount(leftLine);
                    leftColumn = max_column;
                }
            }

            //移动了左光标
            MoveLeftCursor = true;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示左光标的位置
            ensureLeftCursorVisible(cursor);
        }
    }

    private void SelectRight() {
        Cursor cursor = getCursor();
        int leftLine = cursor.getLeftLine();
        int leftColumn = cursor.getLeftColumn();

        int rightLine = cursor.getRightLine();
        int rightColumn = cursor.getRightColumn();

        //选择状态
        if (cursor.isSelected() && MoveLeftCursor) {
            leftColumn++;
            int max_column = getText().getColumnCount(leftLine);
            if (leftColumn > max_column) {
                int max_line = getText().getLineCount() - 1;
                leftLine = leftLine < max_line ? leftLine + 1: max_line;
                leftColumn = 0;//换行为0
            }
            //移动了左光标
            MoveLeftCursor = true;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示左光标的位置
            ensureLeftCursorVisible(cursor);
        }
        else {
            //右移+1
            rightColumn++;
            int max_column = getText().getColumnCount(rightLine);
            if (rightColumn > max_column) {
                int max_line = getText().getLineCount() - 1;
                rightLine = rightLine < max_line ? rightLine + 1: max_line;
                //rightLine改变 max_column刷新
                max_column = getText().getColumnCount(rightLine);
                if (rightLine == max_line) {
                    rightColumn = max_column;
                }
                else {
                    rightColumn = 0;
                }
            }
            //移动了右光标
            MoveLeftCursor = false;
            setSelection(leftLine, leftColumn, rightLine, rightColumn);
            //显示右光标的位置
            ensureRightCursorVisible(cursor);
        }
    }
    //默认不显示光标位置
    private void setSelection(int lineLeft, int columnLeft, int lineRight, int columnRight) {
        setSelectionRegion(lineLeft, columnLeft, lineRight, columnRight, false);
    }

    private void ensureLeftCursorVisible(Cursor cursor) {
        ensurePositionVisible(cursor.getLeftLine(), cursor.getLeftColumn());
    }
    private void ensureRightCursorVisible(Cursor cursor) {
        ensurePositionVisible(cursor.getRightLine(), cursor.getRightColumn());
    }

**Comment by Rosemoe** [comment]
Fixed in latest commit
