### ISSUE TITLE
missing indent in java language

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#66]
Hi, 
when i use java language, no indents are added for commented lines (multi-line comments).

![1630480271](https://user-images.githubusercontent.com/81700082/120891892-1a721480-c61c-11eb-9470-2e9e865a6c21.jpg)

**Comment by Rosemoe** [comment]
It works fine on my device?
![image](https://user-images.githubusercontent.com/28822819/120891986-56b66c80-c63e-11eb-831a-7747b07114ae.png)

**Comment by aliveness-e** [comment]
sorry, my bad :), this bug seems to in a feature that I've added to the editor.
Thanks anyway.

**Comment by Rosemoe** [comment]
You're welcome
