### ISSUE TITLE
Code Editor crashes when press enter (new line)

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#67]
Hi,
i found a bug. every time i press enter (new line) from my keyboard, it carshes.

![Screenshot_20210605-214135](https://user-images.githubusercontent.com/81700082/120900660-17404e00-c647-11eb-89cf-6f99dd9d7c81.png)

(I'm using Google Keyboard)

**Comment by aliveness-e** [comment]
I temporarily solved it using this code that checks if the event is null or not :

`event!=null? event.getKeyCode() : KeyEvent.KEYCODE_ENTER`

I don't know if this is the right way to do it or whether it would cause any other problems or misbehaviour though :) , but it seems working just fine (at least for now).

**Comment by Rosemoe** [comment]
It's okay. I'll make a fake KeyEvent to avoid passing null to the method later.
