### ISSUE TITLE
Auto complete feature.

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#68]
Hi,
Can we customize the contents of the auto complete panel? like when i type "TextView." then it will show options related to "TextView" , like setBackgroundColor, setText,...etc. can we do that?

**Comment by Rosemoe** [comment]
Yes. You are able to do that.
But it is complex.
You probably need to use a cached AST to provide exact proposals.

**Comment by aliveness-e** [comment]
I will try to implement a custom AutoCompleteProvider and see how far i can get :)
Thanks for this awesome and fixable library !.

**Comment by aliveness-e** [comment]
I need some information about this method :
`getAutoCompleteItems(String prefix, boolean isInCodeBlock, TextAnalyzeResult colors, int line) `
prefix is the word that being written, right? 
what is isInCodeBlock?

let's say i typed : `TextView.se`
as the cursor is right at the letter "e" from the incomplete word "set", what would each parameter from the previous method be?

**Comment by itsaky** [comment]
`prefix` depends on what you return in your language's `isAutoCompleteChar(char ch)` method. `isAutoCompleteChar` decides which character should be considered as an auto complete character. If your `isAutoCompleteChar` method is something like this :
```java
@Override
public boolean isAutoCompleteChar(char ch) {
    return MyCharacter.isJavaIdentifierPart(ch);
}
```
and you type `TextView.se` then the `prefix` variable will be `se`. The editor searches backwards from the current cursor position until it finds a character which isn't an auto complete char. Now if you modify the method to return something like this :
```java
return MyCharacter.isJavaIdentifierPart(ch) || ch == '.';
```
then prefix will contain `TextView.se`.

`isInCodeBlock` will be `true` if the cursor is between a `{` and `}`.
`colors` variable contains the span data and may contain extra data which you can set in your analyzer (Read [this](https://github.com/Rosemoe/CodeEditor/wiki/How-to-customize-your-language-for-editor#advanced-method---for-experts) section of the WiKi)
`line` is the line in which the cursor is present.

@Rosemoe Correct me if I'm wrong...

**Comment by aliveness-e** [comment]
it's clear enough now, thank you for your help.

**Comment by Rosemoe** [comment]
> `prefix` depends on what you return in your language's `isAutoCompleteChar(char ch)` method. `isAutoCompleteChar` decides which character should be considered as an auto complete character. If your `isAutoCompleteChar` method is something like this :
> 
> ```java
> @Override
> public boolean isAutoCompleteChar(char ch) {
>     return MyCharacter.isJavaIdentifierPart(ch);
> }
> ```
> 
> and you type `TextView.se` then the `prefix` variable will be `se`. The editor searches backwards from the current cursor position until it finds a character which isn't an auto complete char. Now if you modify the method to return something like this :
> 
> ```java
> return MyCharacter.isJavaIdentifierPart(ch) || ch == '.';
> ```
> 
> then prefix will contain `TextView.se`.
> 
> `isInCodeBlock` will be `true` if the cursor is between a `{` and `}`.
> `colors` variable contains the span data and may contain extra data which you can set in your analyzer (Read [this](https://github.com/Rosemoe/CodeEditor/wiki/How-to-customize-your-language-for-editor#advanced-method---for-experts) section of the WiKi)
> `line` is the line in which the cursor is present.
> 
> @Rosemoe Correct me if I'm wrong...

Yes, that's all right
