### ISSUE TITLE
inserting text in the wrong position

### ISSUE THREAD

**Issue by aliveness-e** [Rosemoe/CodeEditor#69]
Hi,
there is a strange bug that i noticed as I'm using this library. see the videos below.
it inserts text in the wrong position for some reason.

https://user-images.githubusercontent.com/81700082/120995082-21bd2d80-c796-11eb-9659-63cc2f372571.mp4

https://user-images.githubusercontent.com/81700082/120995103-25e94b00-c796-11eb-9ccb-6279ba7d6f01.mp4

**Comment by Rosemoe** [comment]
It's strange.
Does the bug exist before?
Or after certain commit/keyboard software or settings update ?

**Comment by aliveness-e** [comment]
well, it does, it actually exist even before 0.4.0 release i guess. I'm using an app that has this library from last year, and the bug exists there!.
I honestly noticed some misplaced characters in my code sometimes, but never got to know why and when that happened, i would've report them but i had no information about it.

**Comment by aliveness-e** [comment]
Also, it seems to happen when i use Google Keyboard only!, when i switch to other keyboard (Samsung Keyboard), it doesn't occur.

**Comment by Rosemoe** [comment]
Yes, I 'm reproduced the bug in Gboard
I'll find why and fix it soon
