### ISSUE TITLE
Its showing  blue color effect when click on CodeEditor

### ISSUE THREAD

**Issue by RockAriful** [Rosemoe/CodeEditor#73]
![Screenshot_2021-07-06-03-19-35-95](https://user-images.githubusercontent.com/69248471/124519722-edc43f00-de0b-11eb-9758-60ef8312e249.jpg)
How to remove this  blue color effect?

**Comment by Rosemoe** [comment]
Try to call
setDefaultFocusHighlightEnabled(false);
on editor. maybe.
It is drawn by Android framework.
If this can not be solved by doing so, I'll override draw method

**Comment by RockAriful** [comment]
Thanks a lot its working 😍.

**Comment by RockAriful** [comment]
![IMG_20210706_093303](https://user-images.githubusercontent.com/69248471/124538285-2e887c00-de3d-11eb-9298-958c972d658b.jpg)

Another problem, when i press this button of keyboard  text automatically remove/gone😥

**Comment by Rosemoe** [comment]
The problems appear in older versions.
Use newest version instead, please.
Including the background issue, they are solved months ago.

**Comment by RockAriful** [comment]
Thanks ❤️❤️❤️
