### ISSUE TITLE
Add FontStyle for Span.

### ISSUE THREAD

**Issue by Coyamo** [Rosemoe/CodeEditor#98]
- [x] 1. Please add FontStyle for span, such as:

```java
public class FontStyle {
    // This can are bit-flags, so it can be `Italic | Bold`
    public static final int None = 0;
    public static final int Italic = 1;
    public static final int Bold = 2;
    public static final int Underline = 4;
}
```
Or add as flag, like
```java
public static final int FLAG_TYPO = 1 << 1;
```

- [ ] 2. I remember you said that because the initial design of `CodeAnalyzer#underlineColor` was to identify the color of hex color string, it directly passed a color. I think this function should be implemented by externalrenderer. Underlinecolor can consider passing a color ID.

- [ ] 3. Pass an EditorColorScheme for `CodeAnalyzer#analyze(CharSequence,TextAnalyzeResult,TextAnalyzer.AnalyzeThread.Delegate)`.**If the second point is unlikely, add this.**

**Comment by Ninjacoderhsi** [comment]
🤗🤗🤗🤗
